// Mocks generated by Mockito 5.1.0 from annotations
// in blog_graphql_zero/test/features/blog/domain/repositories/post_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:blog_graphql_zero/core/platform/network_info.dart' as _i5;
import 'package:blog_graphql_zero/features/blog/data/datasources/post_remote_datasource.dart'
    as _i2;
import 'package:blog_graphql_zero/features/blog/data/models/post_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [PostRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRemoteDataSource extends _i1.Mock
    implements _i2.PostRemoteDataSource {
  MockPostRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PostModel>> getAllPosts() =>
      (super.noSuchMethod(Invocation.method(#getAllPosts, []),
              returnValue: Future<List<_i4.PostModel>>.value(<_i4.PostModel>[]))
          as _i3.Future<List<_i4.PostModel>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
